name: Build and Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install  # Or any other command to install dependencies

      - name: Build website
        run: npm run build  # Or any other command to build your website

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist  # Change this to the directory containing your built website
          remote-dir: /public_html  # Change this to the remote directory where your website should be deployed
